Repository DistributedCollective/Sovryn-smart-contracts, pull requests merged in 2021-09, with the labels that each got.

#366 Common functionalities
  contracts/mixins/ModuleCommonFunctionalities.sol
  contracts/modules/Affiliates.sol
  contracts/modules/LoanClosingsBase.sol
  contracts/modules/LoanClosingsWith.sol
  contracts/modules/LoanMaintenance.sol
  contracts/modules/LoanOpenings.sol
  contracts/modules/LoanSettings.sol
  contracts/modules/ProtocolSettings.sol
  contracts/modules/SwapsExternal.sol
  scripts/contractInteraction/protocol.py
  scripts/contractInteraction/staking_vesting.py
  scripts/contractInteraction/testnet_contracts.json
Labels: low priority

#365 Change trading rebate rewards SOV become liquid
  contracts/core/State.sol
  contracts/events/FeesEvents.sol
  contracts/events/ProtocolSettingsEvents.sol
  contracts/interfaces/ISovryn.sol
  contracts/mixins/FeesHelper.sol
  contracts/mockup/ProtocolSettingsMockup.sol
  contracts/modules/ProtocolSettings.sol
  interfaces/ISovrynBrownie.sol
  scripts/contractInteraction/protocol.py
  tests/other/ProtocolSettings.test.js
  tests/protocol/ChangeLoanDurationTestToken.test.js
  tests/protocol_settings.js
Labels: high priority

#368 Fix swaps error when sending rbtc
  contracts/swaps/ISwapsImpl.sol
  contracts/swaps/connectors/SwapsImplSovrynSwap.sol
  contracts/swaps/connectors/testnet/SwapsImplLocal.sol
  tests/swaps/SwapsExternal.js
Labels: bug

#369 Update block time
  contracts/governance/StakingRewards/StakingRewards.sol
  scripts/contractInteraction/mainnet_contracts.json
  scripts/contractInteraction/staking_vesting.py
Labels: high priority

#313 Bash script functionSignatures.sh
  package-lock.json
  package.json
  scripts/functionSignatures.sh
  scripts/getSelectors.js
  scripts/keccak256.js
Labels: maintenance

#264 Vesting creator automation
  contracts/governance/Staking/StakingStorage.sol
  contracts/governance/Staking/WeightedStaking.sol
  contracts/governance/Vesting/IVestingRegistry.sol
  contracts/governance/Vesting/VestingCreator.sol
  contracts/governance/Vesting/VestingRegistryLogic.sol
  contracts/governance/Vesting/VestingRegistryProxy.sol
  contracts/governance/Vesting/VestingRegistryStorage.sol
  contracts/mockup/StakingMockup.sol
  contracts/mockup/VestingRegistryLogicMockUp.sol
  scripts/contractInteraction/staking_vesting.py
  scripts/contractInteraction/testnet_contracts.json
  scripts/deployment/deploy_upgradable_vesting_registry.py
  scripts/deployment/distribution/create_vesting_migrations.py
  tests/Governance/GovernorAlpha/ProposeTest.js
  tests/Governance/GovernorAlpha/QueueTest.js
  tests/staking/ExtendedStakingTest.js
  tests/staking/StakingTest.js
  tests/stakingRewards/StakingRewards.js
  tests/vesting/Vesting.js
  tests/vesting/VestingCreator.js
  tests/vesting/VestingRegistryLogic.js
  tests/vesting/VestingRegistryMigrations.js
Labels: enhancement

#376 Add borrower & loan creation time in loan struct data
  contracts/interfaces/ISovryn.sol
  contracts/modules/LoanMaintenance.sol
  interfaces/ISovrynBrownie.sol
  tests/loan-token/tradingFunctions.js
Labels: enhancement, high priority
