Repository DistributedCollective/Sovryn-smart-contracts, pull requests merged in 2021-12, with the labels that each got.

#362 Add test cases for increasing margin trade position
  tests/loan-token/TradingTestToken.test.js
Labels: testing

#398 Add approval event on LoanTokenLogicStandard
  contracts/connectors/loantoken/AdvancedTokenStorage.sol
  contracts/connectors/loantoken/LoanTokenLogicStandard.sol
  contracts/interfaces/ILoanTokenModules.sol
  contracts/testhelpers/TestToken.sol
  tests/loan-token/LendingWithLM.test.js
  tests/loan-token/tokenFunctionality.test.js
  tests/protocol/ChangeLoanDurationTestToken.test.js
Labels: enhancement

#383 Fee sharing proxy amm
  contracts/governance/FeeSharingProxy/FeeSharingLogic.sol
  contracts/governance/FeeSharingProxy/FeeSharingProxyStorage.sol
  contracts/interfaces/IConverterAMM.sol
  contracts/mockup/FeeSharingProxyMockup.sol
  contracts/mockup/LiquidityPoolV1ConverterMockup.sol
  tests/FeeSharingProxyTest.js
Labels: high priority

#403 Fixing math error
  contracts/connectors/loantoken/LoanTokenLogicStandard.sol
  contracts/interfaces/ILoanTokenModules.sol
  scripts/staking/vestings_examples.json
  tests/loan-token/BorrowingTestToken.test.js
  tests/other/OracleIntegration.test.js
  tests/swaps/SwapsExternal.js
  tests/vesting/VestingCreator.js
Labels: meduim priority

#389 Update sip0024 excluding staking
  contracts/governance/StakingRewards/StakingRewards.sol
  contracts/governance/StakingRewards/StakingRewardsStorage.sol
  contracts/governance/Vesting/GenericTokenSender.sol
  contracts/governance/Vesting/TokenSender.sol
  scripts/contractInteraction/ABIs/AMMPriceOracle.json
  scripts/contractInteraction/ABIs/LiquidityPoolV1Converter.json
  scripts/contractInteraction/amm.py
  scripts/contractInteraction/liquidity_mining.py
  scripts/contractInteraction/loan_tokens.py
  scripts/contractInteraction/mainnet_contracts.json
  scripts/contractInteraction/misc.py
  scripts/contractInteraction/multisig.py
  scripts/contractInteraction/prices.py
  scripts/contractInteraction/protocol.py
  scripts/contractInteraction/staking_vesting.py
  scripts/contractInteraction/testnet_contracts.json
  scripts/deployment/distribution/deploy_generic_token_sender.py
  scripts/deployment/distribution/send_tokens.py
  scripts/deployment/distribution/xusd1.csv
  scripts/deployment/liquidity-mining/update-lm.py
  scripts/governance/last_proposal_created.py
  scripts/utils.py
  tests/stakingRewards/Rewards.js
  tests/stakingRewards/StakingRewards.js
  tests/vesting/GenericTokenSender.js
Labels: medium priority
