Repository DistributedCollective/Sovryn-smart-contracts, pull requests merged in 2021-07, with the labels that each got.

#308 Restored lockedSOVFailedMockup
  contracts/mockup/lockedSOVFailedMockup.sol
  tests-js/affiliates_integration.test.js
Labels: low priority

#334 CI Update
  .github/workflows/node.js.yml
  .mocharc.json
  .prettierignore
  .prettierrc
  .solcover.js
  .solhint.json
  .travis.yml
  README.md
  UML.svg
  docs/main.js
  hardhat-ganache-tests.config.js
  interfaces/ISovrynBrownie.sol
  interfaces/IUniswapV2Router01.sol
  interfaces/IUniswapV2Router02.sol
  package.json
  scripts/addLoanToken/README.md
  scripts/contractInteraction/ABIs/FastBTC.json
  scripts/contractInteraction/ABIs/LiquidityPoolV1Converter.json
  scripts/contractInteraction/ABIs/LiquidityPoolV2Converter.json
  scripts/contractInteraction/ABIs/Owned.json
  scripts/contractInteraction/ABIs/RBTCWrapperProxy.json
  scripts/contractInteraction/ABIs/SovrynNft.json
  scripts/contractInteraction/ABIs/SovrynSwapFormula.json
  scripts/contractInteraction/ABIs/SovrynSwapNetwork.json
  scripts/contractInteraction/ABIs/aggregator.json
  scripts/contractInteraction/ABIs/crowd.json
  scripts/contractInteraction/bridge-multisig/Bridge.json
  scripts/contractInteraction/bridge-multisig/Masset.json
  scripts/contractInteraction/mainnet_contracts.json
  scripts/contractInteraction/testnet_contracts.json
  scripts/governance/README.md
  scripts/governance/values.json
  scripts/swapTest/swap_test.json
  scripts/swapTest/swap_test_bpro.json
  scripts/swapTest/swap_test_usdt.json
  scripts/swap_test.json
  scripts/uniswap/README.md
  scripts/uniswap/eth_mainnet_contracts.json
  scripts/uniswap/eth_testnet_contracts.json
  tests-js/Readme.md
  tests/README.md
  truffle-config.js
Labels: documentation, enhancement, maintenance

#322 Reset affiliates reward held if the previous value greater than zero
  contracts/modules/Affiliates.sol
Labels: enhancement

#311 Pause contracts
  contracts/core/State.sol
  contracts/events/ProtocolSettingsEvents.sol
  contracts/interfaces/ISovryn.sol
  contracts/modules/Affiliates.sol
  contracts/modules/LoanClosingsBase.sol
  contracts/modules/LoanClosingsWith.sol
  contracts/modules/LoanMaintenance.sol
  contracts/modules/LoanOpenings.sol
  contracts/modules/LoanSettings.sol
  contracts/modules/ModuleCommonFunctionalities.sol
  contracts/modules/ProtocolSettings.sol
  contracts/modules/SwapsExternal.sol
  interfaces/ISovrynBrownie.sol
  scripts/contractInteraction/protocol.py
  tests-js/PauseModules.test.js
Labels: high priority

#310 Protocol Events
  contracts/events/AffiliatesEvents.sol
  contracts/events/LoanClosingsEvents.sol
  contracts/events/LoanMaintenanceEvents.sol
  contracts/events/LoanOpeningsEvents.sol
  contracts/events/LoanSettingsEvents.sol
  contracts/events/ModulesCommonEvents.sol
  contracts/events/ProtocolSettingsEvents.sol
  contracts/events/SwapsEvents.sol
  contracts/modules/Affiliates.sol
  contracts/modules/LoanClosingsBase.sol
  contracts/modules/LoanClosingsWith.sol
  contracts/modules/LoanMaintenance.sol
  contracts/modules/LoanOpenings.sol
  contracts/modules/LoanSettings.sol
  contracts/modules/ProtocolSettings.sol
  contracts/modules/SwapsExternal.sol
  tests-js/other/Protocol.test.js
Labels: medium priority

#340 Sov staking rewards sip24
  contracts/governance/StakingRewards/StakingRewards.sol
  contracts/governance/StakingRewards/StakingRewardsProxy.sol
  contracts/governance/StakingRewards/StakingRewardsStorage.sol
  contracts/openzeppelin/Initializable.sol
  scripts/contractInteraction/testnet_contracts.json
  scripts/deployment/deploy_sov_staking_rewards.py
  tests-js/stakingRewards/StakingRewards.js
Labels: enhancement, high priority, sip

#327 Events for backend
  contracts/governance/Staking/Checkpoints.sol
  contracts/governance/Staking/Staking.sol
  contracts/mixins/InterestUser.sol
  scripts/contractInteraction/protocol.py
  tests-js/protocol/WithdrawFeesAndInterest.test.js
  tests-js/staking/ExtendedStakingTest.js
Labels: enhancement

#342 Merged dev slippage rebates
  .gitignore
  contracts/connectors/loantoken/LoanTokenLogicStandard.sol
  contracts/connectors/loantoken/LoanTokenLogicWrbtc.sol
  contracts/core/State.sol
  contracts/events/FeesEvents.sol
  contracts/events/ProtocolSettingsEvents.sol
  contracts/feeds/PriceFeeds.sol
  contracts/interfaces/ISovryn.sol
  contracts/mixins/FeesHelper.sol
  contracts/mockup/LockedSOVFailedMockup.sol
  contracts/mockup/ProtocolSettingsMockup.sol
  contracts/modules/LoanClosingsBase.sol
  contracts/modules/LoanClosingsWith.sol
  contracts/modules/LoanMaintenance.sol
  contracts/modules/LoanOpenings.sol
  contracts/modules/ProtocolSettings.sol
  contracts/modules/SwapsExternal.sol
  contracts/swaps/SwapsUser.sol
  contracts/swaps/connectors/SwapsImplSovrynSwap.sol
  interfaces/ISovrynBrownie.sol
  scripts/contractInteraction/protocol.py
  scripts/contractInteraction/testnet_contracts.json
  scripts/deployment/deploy_loanToken.py
  tests-js/PauseModules.test.js
  tests-js/Utils/initializer.js
  tests-js/affiliates.test.js
  tests-js/affiliates_integration.test.js
  tests-js/loan-token/Administration.test.js
  tests-js/loan-token/BorrowingTestToken.test.js
  tests-js/loan-token/LendingTestToken.test.js
  tests-js/loan-token/LendingwRBTCCollateral.test.js
  tests-js/loan-token/LendingwRBTCloan.test.js
  tests-js/loan-token/TradingTestToken.test.js
  tests-js/loan-token/TradingwRBTCCollateral.test.js
  tests-js/loan-token/TradingwRBTCLoan.test.js
  tests-js/loan-token/helpers.js
  tests-js/loan-token/tradingFunctions.js
  tests-js/loan-token/transactionLimit.test.js
  tests-js/margin_trading_boilerplate.test.js
  tests-js/other/LoanOpeningsBorrowOrTradeFromPool.test.js
  tests-js/other/ProtocolSettings.test.js
  tests-js/protocol/ChangeLoanDurationTestToken.test.js
  tests-js/protocol/CloseDepositTestToken.test.js
  tests-js/protocol/DepositCollateralTestToken.test.js
  tests-js/protocol/LiquidationTestToken.test.js
  tests-js/protocol/LiquidationwRBTCAsLoanToken.test.js
  tests-js/protocol/RolloverTestToken.test.js
  tests-js/protocol/WithdrawFeesAndInterest.test.js
  tests-js/protocol/liquidationFunctions.js
  tests-js/swaps/SwapsExternal.js
  tests/fixtures_loan_token.py
  tests/loanToken/administration/test_administration.py
  tests/loanToken/lending/shared_lending_functions.py
  tests/loanToken/trading/shared_trading_functions.py
  tests/protocol/liquidation/shared_liquidation_functions.py
  tests/protocol/rollover/test_rollover_using_TestToken.py
  tests/test_swap.py
Labels: high priority

#344 Fixes for Pausable and SIP-0024
  contracts/governance/Staking/Checkpoints.sol
  contracts/modules/Affiliates.sol
  contracts/modules/ProtocolSettings.sol
  scripts/contractInteraction/protocol.py
  scripts/contractInteraction/testnet_contracts.json
  scripts/deployment/deploy_sov_staking_rewards.py
  tests/staking/ExtendedStakingTest.js
Labels: bug

#345 Integration test scripts after redeployments
  scripts/contractInteraction/loan_tokens.py
Labels: enhancement, high priority

#351 Affiliates:Add view function to get est token rewards value in rbtc
  contracts/interfaces/ISovryn.sol
  contracts/modules/Affiliates.sol
  interfaces/ISovrynBrownie.sol
  tests/affiliates/affiliates_integration.test.js
Labels: enhancement, high priority

#339 In-code documentation for affiliates contract and related
  UML.svg
  contracts/connectors/loantoken/LoanTokenLogicStandard.sol
  contracts/core/State.sol
  contracts/mixins/FeesHelper.sol
  contracts/modules/Affiliates.sol
  contracts/modules/ProtocolSettings.sol
  docs/main.js
  package-lock.json
Labels: documentation

#349 Add rewards owed
  contracts/governance/StakingRewards/StakingRewards.sol
  scripts/contractInteraction/staking_vesting.py
  scripts/contractInteraction/testnet_contracts.json
  tests/stakingRewards/StakingRewards.js
Labels: refactoring

#320 Solidity test coverage
  contracts/testhelpers/TestLibraries.sol
  package-lock.json
  tests/libraries/testLibraries.test.js
  tests/multisig/MultiSigWallet.js
  tests/price-feeds/PriceFeeds.js
  tests/price-feeds/USDTPriceFeed.js
  tests/token/SOVTest.js
Labels: medium priority, testing
